[package]
name = "tempoch-py"
version = "0.1.0"
edition = "2021"
description = "Python bindings for tempoch astronomical time primitives"
license = "AGPL-3.0"
repository = "https://github.com/Siderust/tempoch"
authors = ["VPRamon <vallespuigramon@gmail.com>"]

[lib]
name = "tempoch"  # Python import name
crate-type = ["cdylib"]

[dependencies]
tempoch = { path = "tempoch/tempoch", version = "0.3.0" }
qtty = "0.4.0"
pyo3 = { version = "0.28.2", features = ["extension-module"] }
chrono = "0.4.44"

[dev-dependencies]
pyo3 = { version = "0.28.2", features = ["auto-initialize"] }
approx = "0.5"
